version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # networks:
    #   - mongo-network
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    # restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017
    # networks:
    #   - mongo-network
    ports:
      - "8081:8081"

# networks:
#   mongo-network:
#     driver: bridge
